classdef teStructTreeExplorer < handle
    
    properties
        StructTree struct
    end
    
    properties (Access = private)
        uiParent
        prTree
    end
    
    methods
        
        function obj = teStructTreeExplorer(st, h_parent)
            
            if ~exist('st', 'var') || ~isstruct(st)
                error('Must pass a struct as input to this class.')
            end
            
            if ~exist('h_parent', 'var')
                h_parent = [];
            end
            
            % todo - check class of parent, must be able to contain the
            % appropriate matlab UIxxx objects
            
            obj.StructTree = st;
            obj.uiParent = h_parent;
            obj.UICreate
            
        end
        
        function UICreate(obj, path_root)
            
            % create figure if a parent was not passed
            if isempty(obj.uiParent)
                obj.uiParent = uifigure(...
                    'SizeChangedFcn', @obj.UIResize,...
                    'Visible', 'off',...
                    'AutoResizeChildren', 'off',...
                    'Name', 'Struct Tree Explorer');
            end
            
            % create UI elements
            pos = obj.UIGetPositions;
            
            % data tree
            obj.uiDataTree = teDataTree(obj.uiParent, path_root,...
                pos.uiDataTree);
            
            % summary panel
            obj.uiPnlData = uipanel(obj.uiParent, 'Position', pos.uiPnlData);
            
            % status 
            obj.uiStatus = uilabel(obj.uiParent, 'Position', pos.uiStatus,...
                'Text', '');
            
            % toolbar
            obj.uiToolbar = uipanel(obj.uiParent, 'Position', pos.uiToolbar);
            obj.uiBtnConnectToDatabase = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnConnectToDatabase,...
                'Text', '',...
                'Icon', 'ico_connectToDatabase.png',...
                'Tooltip', 'Connect to database',...
                'Enable', 'on',...       
                'ButtonPushedFcn', @obj.UIBtnConnectToDatabase_Click);
            obj.uiLblDatabaseStatus = uilabel(obj.uiToolbar,...
                'Position', pos.uiLblDatabaseStatus,...
                'Text', sprintf('Database: %s', obj.prClient.Status),...
                'Tooltip', 'Database connection status',...
                'Enable', 'on');            
            obj.uiBtnAddFolder = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnAddFolder,...
                'Text', '',...
                'Icon', 'ico_addFolder.png',...
                'Tooltip', 'Add filesystem folder',...
                'Enable', 'on',...       
                'ButtonPushedFcn', @obj.UIBtnAddFolder_Click);
            obj.uiBtnAddDatabase = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnAddDatabase,...
                'Text', '',...
                'Icon', 'ico_addDatabase.png',...
                'Tooltip', 'Add database connnection',...  
                'Enable', 'off',...
                'ButtonPushedFcn', @obj.UIBtnAddDatabase_Click);
            obj.uiBtnJoin = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnJoin,...
                'Text', '',...
                'Icon', 'ico_join.png',...
                'Tooltip', 'Join sessions',...
                'Enable', 'off',...       
                'ButtonPushedFcn', @obj.UIBtnJoin_Click);
            obj.uiBtnRefreshBranch = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnRefreshBranch,...
                'Text', '',...
                'Icon', 'ico_refresh.png',...
                'Tooltip', 'Refresh current branch',...
                'Enable', 'off',...       
                'ButtonPushedFcn', @obj.UIBtnRefreshBranch_Click);            
            obj.uiBtnInspect = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnInspect,...
                'Text', '',...
                'Icon', 'ico_inspect.png',...
                'Tooltip', 'Inspect selected session(s)',...
                'Enable', 'off',...       
                'ButtonPushedFcn', @obj.UIBtnInspect_Click);               
            obj.uiBtnIngest = uibutton(obj.uiToolbar,...
                'Position', pos.uiBtnIngest,...
                'Text', '',...
                'Icon', 'ico_ingest.png',...
                'Tooltip', 'Ingest selected session(s)',...
                'Enable', 'off',...       
                'ButtonPushedFcn', @obj.UIBtnIngest_Click);     
  
        end
        
    end
    
end
            
            